package example.T1.controllers;

import example.T1.model.User;
import example.T1.repositories.UserRepository;
import example.T1.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;


import java.util.List;
import java.util.Optional;

/**
 * Class which map the paths for operation which are executed on user table
 */
@Component
@RequestMapping("/users")
public class UserController {
    /*@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping({"/"})
    public String selectObjects(){
        return "selectindex";
    }

    @GetMapping({"/allUsers"})
    public ModelAndView getAllUsers() {
        ModelAndView mav = new ModelAndView("index");
        mav.addObject("user", userRepository.findAll());
        return mav;
    }

    @GetMapping(path="/findUser/{id}")
    public @ResponseBody
    Optional<User> getUser(@PathVariable(value = "id") Integer idUser) {
        // This returns a JSON or XML with the users
        return userRepository.findById(idUser);
    }

    @RequestMapping(path="/addOneUser")
    public String saveUser(User user){
        try{
            saveUserinDB(user);
        }catch (Exception e){
            e.printStackTrace();
            return "base";
        }
        return "base";
    }

    public void saveUserinDB(User user){
        userRepository.save(user);
    }

    @GetMapping(path="/updateUser")
    public ModelAndView updateUser(@RequestParam(value = "id") Integer idUser){
        try{
            ModelAndView mav = new ModelAndView("base");
            User user =userRepository.findById(idUser).get();
            mav.addObject("user", user);
            return mav;
        }catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }

    @RequestMapping(path="/deleteUser")
    public String deleteById(@RequestParam(value = "id") Integer idUser){
        try{
            userRepository.deleteById(idUser);
            return "confirm";
        }catch (Exception e){
            e.printStackTrace();
            return "confirm";
        }
    }*/

    UserService userService;

    /**
     *
     * @param userService interface
     */
    public UserController(UserService userService) {
        this.userService = userService;
    }

    /**
     * The function receives a GET request, processes it and gives back a list of User as a response.
     * @return List users
     */
    @GetMapping
    public ResponseEntity<List<User>> getAllUsers(){
        List<User> users = userService.getUsers();
        return new ResponseEntity<>(users, HttpStatus.OK);
    }

    /**
     * The function receives a GET request, processes it, and gives back a list of User as a response.
     * @param idUser integer
     * @return User
     */
    @GetMapping({"/{idUser}"})
    public ResponseEntity<User> getUserByID(@PathVariable Integer idUser){
        return new ResponseEntity<>(userService.getUserByID(idUser), HttpStatus.OK);
    }

    /**
     * The function receives a POST request, processes it, creates a new User and saves it to the database, and returns a resource link to the created user.
     * @param user object
     * @return User
     */
    @PostMapping
    public ResponseEntity<User> createUser(@RequestBody User user){
        User user1 = userService.createUser(user);
        HttpHeaders httpHeaders=new HttpHeaders();
        httpHeaders.add("user", "users"+user1.getIdUser().toString());
        return new ResponseEntity<>(user1, httpHeaders, HttpStatus.CREATED);
    }

    /**
     * The function receives a PUT request, updates the User with the specified Id and returns the updated User
     * @param idUser integer
     * @param user object
     * @return User
     */
    @PutMapping({"/{idUser}"})
    public ResponseEntity<User> updateUser(@PathVariable("idUser") Integer idUser, @RequestBody User user){
        userService.updateUser(idUser, user);
        return new ResponseEntity<>(userService.getUserByID(idUser), HttpStatus.OK);
    }

    /**
     * The function receives a DELETE request, deletes the User with the specified Id.
     * @param idUser integer
     * @return USer
     */
    @DeleteMapping({"/{idUser}"})
    public ResponseEntity<User> deleteUserByID(@PathVariable("idUser") Integer idUser){
        userService.deleteUserByID(idUser);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
